version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017" # Porta padrão do MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Usuário administrador
      MONGO_INITDB_ROOT_PASSWORD: example # Senha do administrador
    volumes:
      - mongodb_data:/data/db # Volume persistente para os dados do MongoDB

volumes:
  mongodb_data:
    driver: local
